import { ObjectId } from "mongodb";
import * as recipesRepo from "../repos/recipesRepo.js";
import * as usersRepo from "../repos/usersRepo.js";

const SEED_TITLES = [
  "Spicy Honey Garlic Chicken Bowl",
  "Creamy Tuscan Pasta",
  "Power Breakfast Wrap",
  "Thai Green Curry",
  "Budget Rice & Beans",
  "Avocado Greek Salad",
  "Overnight Oats Power Jar",
  "Classic Beef Stir-Fry",
  "Smoky Lentil Soup",
  "Teriyaki Salmon Bowl",
];

function buildDocs(ownerId: ObjectId, now: Date) {
  return [
    {
      ownerId,
      title: "Spicy Honey Garlic Chicken Bowl",
      description: "A fiery-sweet weeknight bowl with juicy pan-seared chicken, fluffy rice, and a sticky honey-garlic glaze. Ready in 35 minutes.",
      ingredients: [
        { name: "Chicken breast", amount: "400g" },
        { name: "Cooked white rice", amount: "2 cups" },
        { name: "Garlic cloves", amount: "4 minced" },
        { name: "Honey", amount: "3 tbsp" },
        { name: "Soy sauce", amount: "2 tbsp" },
        { name: "Chili flakes", amount: "1 tsp" },
        { name: "Spring onions", amount: "2 sliced" },
      ],
      steps: [
        "Season chicken with salt, pepper and chili flakes.",
        "Sear chicken in sesame oil over high heat until golden, about 5 min.",
        "Add garlic and cook 1 minute.",
        "Add honey and soy sauce, toss and simmer 2 minutes.",
        "Serve over rice, top with spring onions.",
      ],
      tags: ["quick", "protein", "chicken", "dinner"],
      prepMinutes: 10,
      cookMinutes: 25,
      servings: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      ownerId,
      title: "Creamy Tuscan Pasta",
      description: "Sun-dried tomatoes, baby spinach, and a silky cream sauce in a 25-minute Italian-inspired comfort dish.",
      ingredients: [
        { name: "Fettuccine pasta", amount: "300g" },
        { name: "Heavy cream", amount: "200ml" },
        { name: "Baby spinach", amount: "3 handfuls" },
        { name: "Cherry tomatoes", amount: "150g" },
        { name: "Parmesan", amount: "50g grated" },
        { name: "Garlic", amount: "3 cloves" },
        { name: "Olive oil", amount: "2 tbsp" },
      ],
      steps: [
        "Boil pasta until al dente. Reserve 1/2 cup pasta water.",
        "Sauté garlic in olive oil 1 minute.",
        "Add tomatoes and cook 3 minutes.",
        "Pour in cream, simmer, season.",
        "Add spinach and pasta, toss with pasta water. Top with parmesan.",
      ],
      tags: ["comfort", "vegetarian", "pasta", "dinner"],
      prepMinutes: 5,
      cookMinutes: 20,
      servings: 3,
      createdAt: now,
      updatedAt: now,
    },
    {
      ownerId,
      title: "Power Breakfast Wrap",
      description: "A protein-packed morning wrap with scrambled eggs, fresh spinach, and melted cheddar.",
      ingredients: [
        { name: "Large eggs", amount: "3" },
        { name: "Flour tortillas", amount: "2 large" },
        { name: "Baby spinach", amount: "1 cup" },
        { name: "Cheddar cheese", amount: "50g" },
        { name: "Butter", amount: "1 tsp" },
      ],
      steps: [
        "Whisk eggs with salt and pepper.",
        "Scramble eggs in butter over medium-low heat.",
        "Warm tortilla in dry pan 30 seconds per side.",
        "Layer spinach, eggs, cheese, roll tightly.",
        "Toast seam-down 1 minute until golden.",
      ],
      tags: ["breakfast", "quick", "protein"],
      prepMinutes: 5,
      cookMinutes: 11,
      servings: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      ownerId,
      title: "Thai Green Curry",
      description: "Aromatic Thai green curry with coconut milk, vibrant vegetables. Serve over jasmine rice.",
      ingredients: [
        { name: "Green curry paste", amount: "3 tbsp" },
        { name: "Coconut milk", amount: "400ml" },
        { name: "Chicken or tofu", amount: "350g" },
        { name: "Bell peppers", amount: "2 sliced" },
        { name: "Zucchini", amount: "1 sliced" },
        { name: "Fish sauce", amount: "2 tbsp" },
        { name: "Fresh basil", amount: "handful" },
      ],
      steps: [
        "Fry curry paste in wok 1 minute until fragrant.",
        "Add protein and cook 4 minutes.",
        "Add coconut milk and simmer.",
        "Add vegetables and fish sauce, cook 8 minutes.",
        "Stir in basil and serve over rice.",
      ],
      tags: ["spicy", "comfort", "dinner"],
      prepMinutes: 10,
      cookMinutes: 20,
      servings: 3,
      createdAt: now,
      updatedAt: now,
    },
    {
      ownerId,
      title: "Budget Rice & Beans",
      description: "A hearty, wallet-friendly meal with seasoned black beans over fluffy rice. Under $5 per serving.",
      ingredients: [
        { name: "Canned black beans", amount: "2 × 400g cans" },
        { name: "Long grain rice", amount: "2 cups" },
        { name: "Onion", amount: "1 diced" },
        { name: "Garlic", amount: "2 cloves" },
        { name: "Cumin", amount: "1 tsp" },
        { name: "Smoked paprika", amount: "1 tsp" },
      ],
      steps: [
        "Cook rice per packet instructions.",
        "Sauté onion 4 min, add garlic and spices.",
        "Add beans with liquid, simmer 10 min.",
        "Squeeze lime, season. Serve over rice.",
      ],
      tags: ["budget", "vegan", "healthy"],
      prepMinutes: 5,
      cookMinutes: 20,
      servings: 4,
      createdAt: now,
      updatedAt: now,
    },
    {
      ownerId,
      title: "Avocado Greek Salad",
      description: "Crisp cucumber, ripe tomato, kalamata olives, creamy feta, and avocado in lemon-oregano vinaigrette. No cooking.",
      ingredients: [
        { name: "Cucumber", amount: "1 large diced" },
        { name: "Cherry tomatoes", amount: "200g" },
        { name: "Kalamata olives", amount: "80g" },
        { name: "Feta cheese", amount: "100g" },
        { name: "Avocado", amount: "1 cubed" },
        { name: "Olive oil", amount: "3 tbsp" },
        { name: "Lemon juice", amount: "2 tbsp" },
      ],
      steps: [
        "Combine cucumber, tomatoes, onion, olives.",
        "Whisk oil, lemon, oregano, salt, pepper.",
        "Toss with dressing.",
        "Add avocado and feta on top.",
      ],
      tags: ["healthy", "salad", "vegan", "quick"],
      prepMinutes: 10,
      cookMinutes: 0,
      servings: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      ownerId,
      title: "Overnight Oats Power Jar",
      description: "Creamy overnight oats with chia seeds, banana, and almond butter. Make the night before.",
      ingredients: [
        { name: "Rolled oats", amount: "1 cup" },
        { name: "Almond milk", amount: "1 cup" },
        { name: "Chia seeds", amount: "2 tbsp" },
        { name: "Banana", amount: "1 sliced" },
        { name: "Almond butter", amount: "1 tbsp" },
        { name: "Honey", amount: "1 tsp" },
      ],
      steps: [
        "Combine oats, milk, chia, honey, vanilla in a jar.",
        "Stir, cover, refrigerate overnight.",
        "Top with banana and almond butter in the morning.",
      ],
      tags: ["breakfast", "healthy", "quick"],
      prepMinutes: 5,
      cookMinutes: 0,
      servings: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      ownerId,
      title: "Classic Beef Stir-Fry",
      description: "Tender beef strips with crunchy vegetables in a savory ginger-soy sauce. Faster than delivery.",
      ingredients: [
        { name: "Beef sirloin", amount: "350g sliced" },
        { name: "Broccoli", amount: "2 cups florets" },
        { name: "Bell pepper", amount: "1 sliced" },
        { name: "Soy sauce", amount: "3 tbsp" },
        { name: "Oyster sauce", amount: "2 tbsp" },
        { name: "Fresh ginger", amount: "1 tsp grated" },
        { name: "Garlic", amount: "3 cloves" },
        { name: "Sesame oil", amount: "1 tbsp" },
      ],
      steps: [
        "Mix soy sauce, oyster sauce, ginger, garlic.",
        "Marinate beef 10 min in half the sauce.",
        "Stir-fry beef in sesame oil 3 min. Set aside.",
        "Stir-fry vegetables 3 min.",
        "Return beef, add remaining sauce, toss 1 min. Serve over rice.",
      ],
      tags: ["quick", "protein", "dinner"],
      prepMinutes: 15,
      cookMinutes: 10,
      servings: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      ownerId,
      title: "Smoky Lentil Soup",
      description: "Warming, protein-rich lentil soup with smoked paprika and cumin. Vegan and freezer-friendly.",
      ingredients: [
        { name: "Red lentils", amount: "250g rinsed" },
        { name: "Canned tomatoes", amount: "400g" },
        { name: "Onion", amount: "1 large diced" },
        { name: "Carrots", amount: "2 diced" },
        { name: "Smoked paprika", amount: "2 tsp" },
        { name: "Vegetable stock", amount: "1 litre" },
        { name: "Olive oil", amount: "2 tbsp" },
      ],
      steps: [
        "Sauté onion and carrots in oil 5 min.",
        "Add paprika and cumin, cook 1 min.",
        "Add lentils, tomatoes, stock. Boil.",
        "Simmer 20 min until lentils are soft.",
        "Blend half for creamy texture. Season and serve.",
      ],
      tags: ["vegan", "healthy", "budget", "comfort"],
      prepMinutes: 10,
      cookMinutes: 25,
      servings: 4,
      createdAt: now,
      updatedAt: now,
    },
    {
      ownerId,
      title: "Teriyaki Salmon Bowl",
      description: "Glazed teriyaki salmon over steamed rice with edamame and pickled ginger. Restaurant-quality in 25 minutes.",
      ingredients: [
        { name: "Salmon fillets", amount: "2 × 150g" },
        { name: "Soy sauce", amount: "3 tbsp" },
        { name: "Mirin", amount: "2 tbsp" },
        { name: "Brown sugar", amount: "1 tbsp" },
        { name: "Steamed rice", amount: "2 cups" },
        { name: "Edamame", amount: "100g" },
        { name: "Sesame seeds", amount: "1 tsp" },
      ],
      steps: [
        "Mix soy, mirin, sugar. Simmer 3 min.",
        "Brush salmon with half the glaze.",
        "Pan-fry skin-up 3 min, flip, brush again, cook 3 min.",
        "Serve over rice with edamame, pickled ginger, sesame seeds.",
      ],
      tags: ["protein", "healthy", "quick", "dinner"],
      prepMinutes: 5,
      cookMinutes: 15,
      servings: 2,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export async function seedStarterRecipes(options?: { force?: boolean }): Promise<number> {
  const existing = await recipesRepo.countRecipes();
  if (existing > 0 && !options?.force) {
    return 0;
  }

  const owner = await usersRepo.findUserByEmail("starter@tasteai.local");
  const ownerId = owner?._id ?? new ObjectId();
  const now = new Date();

  if (options?.force && existing > 0) {
    await recipesRepo.deleteManyByTitles(SEED_TITLES);
  }

  return recipesRepo.insertRecipes(buildDocs(ownerId, now));
}
